name: ReadMe Badge
description: Writes coverage badge  to specified files
branding:
  icon: "check-square"
  color: "blue"
inputs:
  coverage:
    description: Code coverage as a percentage in range [0, 100]
    required: true
  color:
    description: Color of badge
    required: false
    default: ""
  change_file:
    description: Markdown files to be modified and has the tags  <!-- Coverage Comment:Begin -->/,/<!-- Coverage Comment:End -->
    required: false
    default: ""
  style:
    description: shields.io style of the badge
    required: false
    default: "for-the-badge"
  repo_token:
    description: GitHub Action token
    default: ${{ github.token }}
  ref:
    description: Branch to commit onto
    default: ${{ github.head_ref }}
outputs:
  badge:
    description: Markdown badge url
    value: ${{ steps.make_badge.outputs.badge }}
runs:
  using: composite
  steps:
    - id: choose_color
      shell: bash
      run: |
        if ${{ inputs.color != '' }}; then
          COLOR="${{ inputs.color }}"
        elif ((100 >= ${{ inputs.coverage }} && ${{ inputs.coverage }} >= 80)); then
          COLOR="green"
        elif ((80 > ${{ inputs.coverage }} && ${{ inputs.coverage }} >= 60)); then
          COLOR="yellow"
        elif ((60 > ${{ inputs.coverage }} && ${{ inputs.coverage }} >= 0)); then
          COLOR="red"
        else
          exit 1
        fi
        echo "coverage=${{ inputs.coverage }}" | sed 's/[^a-z0-9=]*//g' >> $GITHUB_OUTPUT
        echo "color=$COLOR" >> $GITHUB_OUTPUT
    - id: make_badge
      shell: bash
      run: echo "badge=https://img.shields.io/badge/Coverage-${{ steps.choose_color.outputs.coverage }}%25-${{ steps.choose_color.outputs.color }}.svg?style=${{ inputs.style }}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
      if: ${{ inputs.change_file }}
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.repo_token }}
    - id: update_markdown
      if: ${{ inputs.change_file }}
      shell: bash
      run: |
        # Really long command, adds badge with color and coverage between markers in README.md
        sed -i '/<!-- Coverage Comment:Begin -->/,/<!-- Coverage Comment:End -->/c\<!-- Coverage Comment:Begin -->\n[coverage_badge]: ${{ steps.make_badge.outputs.badge }}\n<!-- Coverage Comment:End -->' ${{ inputs.change_file }}
    - uses: stefanzweifel/git-auto-commit-action@v5
      if: ${{ inputs.change_file }}
      with:
        commit_message: Update coverage badge
        branch: ${{ inputs.ref }}
        add_options: '-u'
        commit_options: '--no-verify'

